// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerMigrations
{
    [DbContext(typeof(csMainDbContext.SqlServerDbContext))]
    [Migration("20231116122759_mi_test")]
    partial class mi_test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.TicketTemplateDbM", b =>
                {
                    b.Property<Guid>("TicketTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShowEventInfo")
                        .HasColumnType("int");

                    b.Property<string>("TicketsHandlingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TicketTemplateId");

                    b.ToTable("TicketTemplate");
                });

            modelBuilder.Entity("DbModels.TicketsDataDto", b =>
                {
                    b.Property<int?>("ArtNotText")
                        .HasColumnType("int");

                    b.Property<string>("ArtikelNr")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Artikelnamn")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Beskrivning")
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("BokningsNr")
                        .HasColumnType("money");

                    b.Property<string>("Datum")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ingang")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KontaktPerson")
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Pris")
                        .HasColumnType("money");

                    b.Property<string>("Rutbokstav")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("StrukturArtikel")
                        .HasColumnType("bit");

                    b.Property<string>("Webbcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("anamn")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("datumStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("eMail")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("eventdatum_id")
                        .HasColumnType("int");

                    b.Property<string>("logorad1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("logorad2")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("namn")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("namn1")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("namn2")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("plats")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("platsbokad_id")
                        .HasColumnType("int");

                    b.Property<string>("reklam1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("serviceavgift1_kr")
                        .HasColumnType("money");

                    b.Property<int>("showEventInfo")
                        .HasColumnType("int");

                    b.Property<string>("stolsnr")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("stolsrad")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("wbarticleinfo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("wbeventinfo")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("webbkod")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("Vy_ShowTickets", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
